---
title: Objet Papier
timezone: UTC
collections:
  contributors:
    title: Contributors
    output: true
  op-release:
    title: Op Release
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: contributors
  values:
    title:
    role:
    link:
- scope:
    path: ''
    type: op-release
  values:
    title:
    layout: project
    number:
    auteur:
    - name:
      website:
    name:
    cover-image: op###-cover (Ne pas ajouter l'extension ".jpg" après le nom)
    format:
    nb-pages:
    reliure:
    impression:
    exemplaires:
    prix:
    images:
    - op###-1
    - op###-2
    - op###-3
email: hello@objetpapier.fr
description: Objet Papier est un label de micro édition montreuillois qui publie des
  fanzines de photographies, montages, mots et expérimentations diverses.
baseurl:
url: http://objetpapier.fr/
markdown: kramdown
plugins:
- jekyll-feed
