---
title: Objet Papier
timezone: UTC
collections:
  contributors:
    title: Contributors
    output: false
  experiments:
    title: Op Experiments
    output: false
  op-release:
    title: Op Release
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: contributors
  values:
    title: 
    role: 
    link: 
- scope:
    path: ''
    type: op-release
  values:
    title: 
    layout: project
    number: OP###
    auteur:
    - name: 
      website: 
    name: 
    black-cover-image: op###-cover-black
    white-cover-image: op###-cover-white
    images:
    - "/uploads/op###-1.jpg"
    - "/uploads/op###-2.jpg"
    - "/uploads/op###-3.jpg"
    format: 
    nb-pages: 
    reliure: 
    impression: 
    exemplaires: 
    prix: 5 (ne pas ajouter de symbole "€", si épuisé utiliser "sold-out")
    paypal-link: 
- scope:
    path: ''
    type: experiments
  values:
    exp-number: 
    title: 
    exp-meta:
    - meta-name: 
      meta-content: 
    images:
    - "/uploads/img.jpg"
    video: 
email: hello@objetpapier.fr
description: Objet Papier est un label de micro édition montreuillois qui publie des
  fanzines de photographies, montages, mots et expérimentations diverses.
baseurl: 
url: http://objetpapier.fr
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-assets
