---
title: Objet Papier
timezone: UTC
collections:
  op-release:
    title: Op Release
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@objetpapier.fr
description: Objet Papier est un label de micro édition montreuillois qui publie des
  fanzines de photographies, montages, mots et expérimentations diverses.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
